version: "3"

services:
  db:
    image: postgres:17
    container_name: shorclink_postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      # もしくは、以下のように直接PostgreSQLの環境変数名を.envに書くことも可能です
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: # .env ファイルを読み込むことを明示的に記述します
      - .env
  adminer:
    image: adminer
    container_name: shorclink_adminer
    ports:
      - 8081:8080
    depends_on:
      - db
volumes:
  db-store:
